name: Generate SBOM using Syft

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sbom-syft:
    name: Generate SBOM with Syft
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Python on the GitHub runner
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Create a virtual environment and install requirements if present
      - name: Create Virtual Environment and Install Requirements
        run: |
          python -m venv venv
          source venv/bin/activate
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Install Syft CLI tool
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      # Generate SBOM from current project directory in SPDX format (JSON)
      - name: Generate SBOM (SPDX JSON)
        run: |
          syft . -o spdx-json > sbom.spdx.json

      # Upload the SBOM reports as workflow artifacts
      - name: Upload SBOM Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: syft-sbom-reports
          path: |
            sbom.spdx.json
            sbom.cyclonedx.json
